INSERT INTO sys_apis (created_at, updated_at, path, description, api_group, method)
SELECT NOW(3), NOW(3), src.path, src.description, src.api_group, src.method
FROM (
    SELECT '/deviceCategory/createDeviceCategory' AS path, '创建设备类别' AS description, '设备固件-设备类别' AS api_group, 'POST' AS method
    UNION ALL SELECT '/deviceCategory/deleteDeviceCategory', '删除设备类别', '设备固件-设备类别', 'DELETE'
    UNION ALL SELECT '/deviceCategory/deleteDeviceCategoryByIds', '批量删除设备类别', '设备固件-设备类别', 'DELETE'
    UNION ALL SELECT '/deviceCategory/updateDeviceCategory', '更新设备类别', '设备固件-设备类别', 'PUT'
    UNION ALL SELECT '/deviceCategory/findDeviceCategory', '获取设备类别详情', '设备固件-设备类别', 'GET'
    UNION ALL SELECT '/deviceCategory/getDeviceCategoryList', '获取设备类别列表', '设备固件-设备类别', 'GET'
    UNION ALL SELECT '/deviceModel/createDeviceModel', '创建设备型号', '设备固件-设备型号', 'POST'
    UNION ALL SELECT '/deviceModel/deleteDeviceModel', '删除设备型号', '设备固件-设备型号', 'DELETE'
    UNION ALL SELECT '/deviceModel/deleteDeviceModelByIds', '批量删除设备型号', '设备固件-设备型号', 'DELETE'
    UNION ALL SELECT '/deviceModel/updateDeviceModel', '更新设备型号', '设备固件-设备型号', 'PUT'
    UNION ALL SELECT '/deviceModel/findDeviceModel', '获取设备型号详情', '设备固件-设备型号', 'GET'
    UNION ALL SELECT '/deviceModel/getDeviceModelList', '获取设备型号列表', '设备固件-设备型号', 'GET'
    UNION ALL SELECT '/firmwareVersion/createFirmwareVersion', '创建固件版本', '设备固件-固件版本', 'POST'
    UNION ALL SELECT '/firmwareVersion/deleteFirmwareVersion', '删除固件版本', '设备固件-固件版本', 'DELETE'
    UNION ALL SELECT '/firmwareVersion/deleteFirmwareVersionByIds', '批量删除固件版本', '设备固件-固件版本', 'DELETE'
    UNION ALL SELECT '/firmwareVersion/updateFirmwareVersion', '更新固件版本', '设备固件-固件版本', 'PUT'
    UNION ALL SELECT '/firmwareVersion/findFirmwareVersion', '获取固件版本详情', '设备固件-固件版本', 'GET'
    UNION ALL SELECT '/firmwareVersion/getFirmwareVersionList', '获取固件版本列表', '设备固件-固件版本', 'GET'
    UNION ALL SELECT '/firmwareVersion/changeFirmwareVersionStatus', '更新固件版本状态', '设备固件-固件版本', 'POST'
    UNION ALL SELECT '/modelFirmware/createModelFirmwareRel', '创建型号固件关系', '设备固件-型号关系', 'POST'
    UNION ALL SELECT '/modelFirmware/deleteModelFirmwareRel', '删除型号固件关系', '设备固件-型号关系', 'DELETE'
    UNION ALL SELECT '/modelFirmware/deleteModelFirmwareRelByIds', '批量删除型号固件关系', '设备固件-型号关系', 'DELETE'
    UNION ALL SELECT '/modelFirmware/updateModelFirmwareRel', '更新型号固件关系', '设备固件-型号关系', 'PUT'
    UNION ALL SELECT '/modelFirmware/findModelFirmwareRel', '获取型号固件关系详情', '设备固件-型号关系', 'GET'
    UNION ALL SELECT '/modelFirmware/getModelFirmwareRelList', '获取型号固件关系列表', '设备固件-型号关系', 'GET'
    UNION ALL SELECT '/modelFirmware/setModelFirmwareRecommended', '设置推荐版本', '设备固件-型号关系', 'POST'
    UNION ALL SELECT '/modelFirmware/setModelFirmwareTestResult', '设置测试结果', '设备固件-型号关系', 'POST'
    UNION ALL SELECT '/firmwareTag/createFirmwareTag', '创建固件标签', '设备固件-标签', 'POST'
    UNION ALL SELECT '/firmwareTag/deleteFirmwareTag', '删除固件标签', '设备固件-标签', 'DELETE'
    UNION ALL SELECT '/firmwareTag/deleteFirmwareTagByIds', '批量删除固件标签', '设备固件-标签', 'DELETE'
    UNION ALL SELECT '/firmwareTag/updateFirmwareTag', '更新固件标签', '设备固件-标签', 'PUT'
    UNION ALL SELECT '/firmwareTag/findFirmwareTag', '获取固件标签详情', '设备固件-标签', 'GET'
    UNION ALL SELECT '/firmwareTag/getFirmwareTagList', '获取固件标签列表', '设备固件-标签', 'GET'
    UNION ALL SELECT '/firmwareTag/setFirmwareTags', '设置固件标签', '设备固件-标签', 'POST'
    UNION ALL SELECT '/firmwareVersionLog/findFirmwareVersionLog', '获取固件日志详情', '设备固件-日志', 'GET'
    UNION ALL SELECT '/firmwareVersionLog/getFirmwareVersionLogList', '获取固件日志列表', '设备固件-日志', 'GET'
) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM sys_apis t
    WHERE t.path = src.path AND t.method = src.method
);

INSERT INTO casbin_rule (ptype, v0, v1, v2)
SELECT src.ptype, src.v0, src.v1, src.v2
FROM (
    SELECT 'p' AS ptype, '888' AS v0, '/deviceCategory/createDeviceCategory' AS v1, 'POST' AS v2
    UNION ALL SELECT 'p', '888', '/deviceCategory/deleteDeviceCategory', 'DELETE'
    UNION ALL SELECT 'p', '888', '/deviceCategory/deleteDeviceCategoryByIds', 'DELETE'
    UNION ALL SELECT 'p', '888', '/deviceCategory/updateDeviceCategory', 'PUT'
    UNION ALL SELECT 'p', '888', '/deviceCategory/findDeviceCategory', 'GET'
    UNION ALL SELECT 'p', '888', '/deviceCategory/getDeviceCategoryList', 'GET'
    UNION ALL SELECT 'p', '888', '/deviceModel/createDeviceModel', 'POST'
    UNION ALL SELECT 'p', '888', '/deviceModel/deleteDeviceModel', 'DELETE'
    UNION ALL SELECT 'p', '888', '/deviceModel/deleteDeviceModelByIds', 'DELETE'
    UNION ALL SELECT 'p', '888', '/deviceModel/updateDeviceModel', 'PUT'
    UNION ALL SELECT 'p', '888', '/deviceModel/findDeviceModel', 'GET'
    UNION ALL SELECT 'p', '888', '/deviceModel/getDeviceModelList', 'GET'
    UNION ALL SELECT 'p', '888', '/firmwareVersion/createFirmwareVersion', 'POST'
    UNION ALL SELECT 'p', '888', '/firmwareVersion/deleteFirmwareVersion', 'DELETE'
    UNION ALL SELECT 'p', '888', '/firmwareVersion/deleteFirmwareVersionByIds', 'DELETE'
    UNION ALL SELECT 'p', '888', '/firmwareVersion/updateFirmwareVersion', 'PUT'
    UNION ALL SELECT 'p', '888', '/firmwareVersion/findFirmwareVersion', 'GET'
    UNION ALL SELECT 'p', '888', '/firmwareVersion/getFirmwareVersionList', 'GET'
    UNION ALL SELECT 'p', '888', '/firmwareVersion/changeFirmwareVersionStatus', 'POST'
    UNION ALL SELECT 'p', '888', '/modelFirmware/createModelFirmwareRel', 'POST'
    UNION ALL SELECT 'p', '888', '/modelFirmware/deleteModelFirmwareRel', 'DELETE'
    UNION ALL SELECT 'p', '888', '/modelFirmware/deleteModelFirmwareRelByIds', 'DELETE'
    UNION ALL SELECT 'p', '888', '/modelFirmware/updateModelFirmwareRel', 'PUT'
    UNION ALL SELECT 'p', '888', '/modelFirmware/findModelFirmwareRel', 'GET'
    UNION ALL SELECT 'p', '888', '/modelFirmware/getModelFirmwareRelList', 'GET'
    UNION ALL SELECT 'p', '888', '/modelFirmware/setModelFirmwareRecommended', 'POST'
    UNION ALL SELECT 'p', '888', '/modelFirmware/setModelFirmwareTestResult', 'POST'
    UNION ALL SELECT 'p', '888', '/firmwareTag/createFirmwareTag', 'POST'
    UNION ALL SELECT 'p', '888', '/firmwareTag/deleteFirmwareTag', 'DELETE'
    UNION ALL SELECT 'p', '888', '/firmwareTag/deleteFirmwareTagByIds', 'DELETE'
    UNION ALL SELECT 'p', '888', '/firmwareTag/updateFirmwareTag', 'PUT'
    UNION ALL SELECT 'p', '888', '/firmwareTag/findFirmwareTag', 'GET'
    UNION ALL SELECT 'p', '888', '/firmwareTag/getFirmwareTagList', 'GET'
    UNION ALL SELECT 'p', '888', '/firmwareTag/setFirmwareTags', 'POST'
    UNION ALL SELECT 'p', '888', '/firmwareVersionLog/findFirmwareVersionLog', 'GET'
    UNION ALL SELECT 'p', '888', '/firmwareVersionLog/getFirmwareVersionLogList', 'GET'
    UNION ALL SELECT 'p', '8881', '/deviceCategory/createDeviceCategory', 'POST'
    UNION ALL SELECT 'p', '8881', '/deviceCategory/deleteDeviceCategory', 'DELETE'
    UNION ALL SELECT 'p', '8881', '/deviceCategory/deleteDeviceCategoryByIds', 'DELETE'
    UNION ALL SELECT 'p', '8881', '/deviceCategory/updateDeviceCategory', 'PUT'
    UNION ALL SELECT 'p', '8881', '/deviceCategory/findDeviceCategory', 'GET'
    UNION ALL SELECT 'p', '8881', '/deviceCategory/getDeviceCategoryList', 'GET'
    UNION ALL SELECT 'p', '8881', '/deviceModel/createDeviceModel', 'POST'
    UNION ALL SELECT 'p', '8881', '/deviceModel/deleteDeviceModel', 'DELETE'
    UNION ALL SELECT 'p', '8881', '/deviceModel/deleteDeviceModelByIds', 'DELETE'
    UNION ALL SELECT 'p', '8881', '/deviceModel/updateDeviceModel', 'PUT'
    UNION ALL SELECT 'p', '8881', '/deviceModel/findDeviceModel', 'GET'
    UNION ALL SELECT 'p', '8881', '/deviceModel/getDeviceModelList', 'GET'
    UNION ALL SELECT 'p', '8881', '/firmwareVersion/createFirmwareVersion', 'POST'
    UNION ALL SELECT 'p', '8881', '/firmwareVersion/deleteFirmwareVersion', 'DELETE'
    UNION ALL SELECT 'p', '8881', '/firmwareVersion/deleteFirmwareVersionByIds', 'DELETE'
    UNION ALL SELECT 'p', '8881', '/firmwareVersion/updateFirmwareVersion', 'PUT'
    UNION ALL SELECT 'p', '8881', '/firmwareVersion/findFirmwareVersion', 'GET'
    UNION ALL SELECT 'p', '8881', '/firmwareVersion/getFirmwareVersionList', 'GET'
    UNION ALL SELECT 'p', '8881', '/firmwareVersion/changeFirmwareVersionStatus', 'POST'
    UNION ALL SELECT 'p', '8881', '/modelFirmware/createModelFirmwareRel', 'POST'
    UNION ALL SELECT 'p', '8881', '/modelFirmware/deleteModelFirmwareRel', 'DELETE'
    UNION ALL SELECT 'p', '8881', '/modelFirmware/deleteModelFirmwareRelByIds', 'DELETE'
    UNION ALL SELECT 'p', '8881', '/modelFirmware/updateModelFirmwareRel', 'PUT'
    UNION ALL SELECT 'p', '8881', '/modelFirmware/findModelFirmwareRel', 'GET'
    UNION ALL SELECT 'p', '8881', '/modelFirmware/getModelFirmwareRelList', 'GET'
    UNION ALL SELECT 'p', '8881', '/modelFirmware/setModelFirmwareRecommended', 'POST'
    UNION ALL SELECT 'p', '8881', '/modelFirmware/setModelFirmwareTestResult', 'POST'
    UNION ALL SELECT 'p', '8881', '/firmwareTag/createFirmwareTag', 'POST'
    UNION ALL SELECT 'p', '8881', '/firmwareTag/deleteFirmwareTag', 'DELETE'
    UNION ALL SELECT 'p', '8881', '/firmwareTag/deleteFirmwareTagByIds', 'DELETE'
    UNION ALL SELECT 'p', '8881', '/firmwareTag/updateFirmwareTag', 'PUT'
    UNION ALL SELECT 'p', '8881', '/firmwareTag/findFirmwareTag', 'GET'
    UNION ALL SELECT 'p', '8881', '/firmwareTag/getFirmwareTagList', 'GET'
    UNION ALL SELECT 'p', '8881', '/firmwareTag/setFirmwareTags', 'POST'
    UNION ALL SELECT 'p', '8881', '/firmwareVersionLog/findFirmwareVersionLog', 'GET'
    UNION ALL SELECT 'p', '8881', '/firmwareVersionLog/getFirmwareVersionLogList', 'GET'
    UNION ALL SELECT 'p', '9528', '/deviceCategory/createDeviceCategory', 'POST'
    UNION ALL SELECT 'p', '9528', '/deviceCategory/deleteDeviceCategory', 'DELETE'
    UNION ALL SELECT 'p', '9528', '/deviceCategory/deleteDeviceCategoryByIds', 'DELETE'
    UNION ALL SELECT 'p', '9528', '/deviceCategory/updateDeviceCategory', 'PUT'
    UNION ALL SELECT 'p', '9528', '/deviceCategory/findDeviceCategory', 'GET'
    UNION ALL SELECT 'p', '9528', '/deviceCategory/getDeviceCategoryList', 'GET'
    UNION ALL SELECT 'p', '9528', '/deviceModel/createDeviceModel', 'POST'
    UNION ALL SELECT 'p', '9528', '/deviceModel/deleteDeviceModel', 'DELETE'
    UNION ALL SELECT 'p', '9528', '/deviceModel/deleteDeviceModelByIds', 'DELETE'
    UNION ALL SELECT 'p', '9528', '/deviceModel/updateDeviceModel', 'PUT'
    UNION ALL SELECT 'p', '9528', '/deviceModel/findDeviceModel', 'GET'
    UNION ALL SELECT 'p', '9528', '/deviceModel/getDeviceModelList', 'GET'
    UNION ALL SELECT 'p', '9528', '/firmwareVersion/createFirmwareVersion', 'POST'
    UNION ALL SELECT 'p', '9528', '/firmwareVersion/deleteFirmwareVersion', 'DELETE'
    UNION ALL SELECT 'p', '9528', '/firmwareVersion/deleteFirmwareVersionByIds', 'DELETE'
    UNION ALL SELECT 'p', '9528', '/firmwareVersion/updateFirmwareVersion', 'PUT'
    UNION ALL SELECT 'p', '9528', '/firmwareVersion/findFirmwareVersion', 'GET'
    UNION ALL SELECT 'p', '9528', '/firmwareVersion/getFirmwareVersionList', 'GET'
    UNION ALL SELECT 'p', '9528', '/firmwareVersion/changeFirmwareVersionStatus', 'POST'
    UNION ALL SELECT 'p', '9528', '/modelFirmware/createModelFirmwareRel', 'POST'
    UNION ALL SELECT 'p', '9528', '/modelFirmware/deleteModelFirmwareRel', 'DELETE'
    UNION ALL SELECT 'p', '9528', '/modelFirmware/deleteModelFirmwareRelByIds', 'DELETE'
    UNION ALL SELECT 'p', '9528', '/modelFirmware/updateModelFirmwareRel', 'PUT'
    UNION ALL SELECT 'p', '9528', '/modelFirmware/findModelFirmwareRel', 'GET'
    UNION ALL SELECT 'p', '9528', '/modelFirmware/getModelFirmwareRelList', 'GET'
    UNION ALL SELECT 'p', '9528', '/modelFirmware/setModelFirmwareRecommended', 'POST'
    UNION ALL SELECT 'p', '9528', '/modelFirmware/setModelFirmwareTestResult', 'POST'
    UNION ALL SELECT 'p', '9528', '/firmwareTag/createFirmwareTag', 'POST'
    UNION ALL SELECT 'p', '9528', '/firmwareTag/deleteFirmwareTag', 'DELETE'
    UNION ALL SELECT 'p', '9528', '/firmwareTag/deleteFirmwareTagByIds', 'DELETE'
    UNION ALL SELECT 'p', '9528', '/firmwareTag/updateFirmwareTag', 'PUT'
    UNION ALL SELECT 'p', '9528', '/firmwareTag/findFirmwareTag', 'GET'
    UNION ALL SELECT 'p', '9528', '/firmwareTag/getFirmwareTagList', 'GET'
    UNION ALL SELECT 'p', '9528', '/firmwareTag/setFirmwareTags', 'POST'
    UNION ALL SELECT 'p', '9528', '/firmwareVersionLog/findFirmwareVersionLog', 'GET'
    UNION ALL SELECT 'p', '9528', '/firmwareVersionLog/getFirmwareVersionLogList', 'GET'
) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM casbin_rule t
    WHERE t.ptype = src.ptype AND t.v0 = src.v0 AND t.v1 = src.v1 AND t.v2 = src.v2
);
